In [66]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
from sklearn import datasets
from sklearn import metrics

In [67]:
#loading dataset
dataset = pd.read_csv('Credit.csv')
X= dataset.iloc[:,:-1].values
y= dataset.iloc[:,24].values

In [68]:
dataset.head(5)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1    20000.0    2          2         1   24      2      2     -1     -1   
1   2   120000.0    2          2         2   26     -1      2      0      0   
2   3    90000.0    2          2         2   34      0      0      0      0   
3   4    50000.0    2          2         1   37      0      0      0      0   
4   5    50000.0    1          2         1   57     -1      0     -1      0   

   ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0  ...        0.0        0.0        0.0       0.0     689.0       0.0   
1  ...     3272.0     3455.0     3261.0       0.0    1000.0    1000.0   
2  ...    14331.0    14948.0    15549.0    1518.0    1500.0    1000.0   
3  ...    28314.0    28959.0    29547.0    2000.0    2019.0    1200.0   
4  ...    20940.0    19146.0    19131.0    2000.0   36681.0   10000.0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
0       0.0       0.0       0.0                           1  
1    1000.0       0.0    2000.0                           1  
2    1000.0    1000.0    5000.0                           0  
3    1100.0    1069.0    1000.0                           0  
4    9000.0     689.0     679.0                           0  

[5 rows x 25 columns]

In [69]:
dataset.tail(5)

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
29995  29996   220000.0    1          3         1   39      0      0      0   
29996  29997   150000.0    1          3         2   43     -1     -1     -1   
29997  29998    30000.0    1          2         2   37      4      3      2   
29998  29999    80000.0    1          3         1   41      1     -1      0   
29999  30000    50000.0    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
29995      0  ...    88004.0    31237.0    15980.0    8500.0   20000.0   
29996     -1  ...     8979.0     5190.0        0.0    1837.0    3526.0   
29997     -1  ...    20878.0    20582.0    19357.0       0.0       0.0   
29998      0  ...    52774.0    11855.0    48944.0   85900.0    3409.0   
29999      0  ...    36535.0    32428.0    15313.0    2078.0    1800.0   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default.payment.next.month  
29995    5003.0    3047.0    5000.0    1000.0                           0  
29996    8998.0     129.0       0.0       0.0                           0  
29997   22000.0    4200.0    2000.0    3100.0                           1  
29998    1178.0    1926.0   52964.0    1804.0                           1  
29999    1430.0    1000.0    1000.0    1000.0                           1  

[5 rows x 25 columns]

In [138]:
dataset.describe()

ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867   
std     8660.398374   129747.661567      0.489129      0.790349      0.521970   
min        1.000000    10000.000000      1.000000      0.000000      0.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                AGE         PAY_0         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

       ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6  default.payment.next.month  
count   30000.000000                30000.000000  
mean     5215.502567                    0.221200  
std     17777.465775                    0.415062  
min         0.000000                    0.000000  
25%       117.750000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000  

[8 rows x 25 columns]

In [70]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 82)

In [71]:
# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [72]:
conda install tensorflow

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda




In [73]:
conda install keras

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 22.11.1

Please update conda by running

    $ conda update -n base -c defaults conda




# Artifical Neural network Implementation

In [74]:
#Applying ANN

import keras
from keras.models import Sequential
from keras.layers import Dense

In [75]:
classifier = Sequential()

In [76]:
classifier.add(Dense(12, activation= 'relu'))

In [77]:
classifier.add(Dense(7, activation= 'relu'))

In [78]:
classifier.add(Dense(1 ,activation= 'sigmoid'))

In [79]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [80]:
classifier.fit(X_train, y_train,batch_size=10)

2250/2250 [==============================] - 2s 771us/step - loss: 0.4815 - accuracy: 0.7964


In [81]:
#predicting the test set result

y_pred=classifier.predict(X_test)

In [82]:
y_pred=(y_pred>0.5)

In [83]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

In [84]:
cm=confusion_matrix(y_test,y_pred)

In [85]:
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89      5880
           1       0.67      0.31      0.42      1620

    accuracy                           0.82      7500
   macro avg       0.75      0.63      0.66      7500
weighted avg       0.80      0.82      0.79      7500



In [86]:
print(metrics.confusion_matrix(y_test,y_pred ))

[[5639  241]
 [1123  497]]


# KNN Implementation

In [87]:
from sklearn.neighbors import KNeighborsClassifier

In [88]:
classifier = KNeighborsClassifier()

In [89]:
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [90]:
predictions = classifier.predict(X_test)

In [91]:
from sklearn.metrics import accuracy_score

In [92]:
print (accuracy_score(y_test, predictions))

0.7962666666666667


In [93]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

In [94]:
print (accuracy_score(y_test, predictions))

0.7962666666666667


In [95]:
print(metrics.classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.84      0.92      0.88      5880
           1       0.55      0.34      0.42      1620

    accuracy                           0.80      7500
   macro avg       0.69      0.63      0.65      7500
weighted avg       0.77      0.80      0.78      7500



In [96]:
print(metrics.confusion_matrix(y_test, predictions))

[[5418  462]
 [1066  554]]


# SVM Implementation

In [97]:
#Applying SVM Algorithm

# set model, fit and predict
from sklearn.svm import SVC

In [98]:
svm = SVC(kernel='rbf')

In [99]:
svm.fit(X_train, y_train)

SVC()

In [100]:
# Predicting the Test set results
y_prediction = svm.predict(X_test)
print(y_prediction)

[0 1 0 ... 0 1 1]


In [101]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_prediction)).T

In [102]:
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0]], dtype=int64)

In [103]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [104]:
print (accuracy_score(y_test, y_prediction))

0.822


In [105]:
print(metrics.classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

           0       0.84      0.96      0.89      5880
           1       0.68      0.33      0.44      1620

    accuracy                           0.82      7500
   macro avg       0.76      0.64      0.67      7500
weighted avg       0.80      0.82      0.80      7500



In [106]:
print(metrics.confusion_matrix(y_test, y_prediction))

[[5636  244]
 [1091  529]]


In [107]:
cm = confusion_matrix(y_test, y_prediction)

In [108]:
print(cm)

[[5636  244]
 [1091  529]]


# RandomForest Implementation

In [109]:
#Applying Rndom Forest
from sklearn.ensemble import RandomForestClassifier

In [110]:
# set model, fit and predict
rfc = RandomForestClassifier(max_depth=10, random_state=0)

In [111]:
rfc.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=0)

In [112]:
# Predicting the Test set results
y_prediction = rfc.predict(X_test)
print(y_prediction)

[0 1 0 ... 0 1 1]


In [113]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_prediction)).T

In [114]:
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[1, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0]], dtype=int64)

In [115]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [116]:
print (accuracy_score(y_test, y_prediction))

0.8222666666666667


In [117]:
print(metrics.classification_report(y_test, y_prediction))

              precision    recall  f1-score   support

           0       0.84      0.95      0.89      5880
           1       0.67      0.35      0.46      1620

    accuracy                           0.82      7500
   macro avg       0.76      0.65      0.68      7500
weighted avg       0.80      0.82      0.80      7500



In [118]:
print(metrics.confusion_matrix(y_test, y_prediction))

[[5600  280]
 [1053  567]]


# Logistic Regression implementation

In [127]:
#applyin logistic regression
from sklearn.linear_model import LogisticRegression

In [128]:
logisticregression = LogisticRegression()

In [129]:
logisticregression.fit(X_train, y_train)

LogisticRegression()

In [130]:
# Predicting the Test set results
y_pred = logisticregression.predict(X_test)
print(y_pred)

[0 1 0 ... 0 1 0]


In [131]:
#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T

In [132]:
#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

array([[1, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0]], dtype=int64)

In [133]:
print (accuracy_score(y_test, y_pred))

0.8146666666666667


In [134]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.97      0.89      5880
           1       0.71      0.24      0.36      1620

    accuracy                           0.81      7500
   macro avg       0.77      0.61      0.62      7500
weighted avg       0.80      0.81      0.78      7500



In [135]:
print(metrics.confusion_matrix(y_test, y_pred))

[[5727  153]
 [1237  383]]


In [136]:
cm = confusion_matrix(y_test, y_pred)

In [137]:
print(cm)

[[5727  153]
 [1237  383]]
